version: '3.8'

services:
  webapp:
    build:
      context: ..
      dockerfile: docker/webapp/Dockerfile.dev
      args:
        - ASSET_PACK_HREF=http://192.168.1.236:${ASSET_PACK_PORT:-7413}/
        - AUTH_SERVER_URL=http://192.168.1.236:${AUTH_PORT:-9413}
        - APP_VERSION=2.7.2
        - ASSET_DIR=/assets/
    ports:
      - "${WEB_PORT:-8413}:${WEB_PORT:-8413}"
    environment:
      - ASSET_PACK_HREF=http://192.168.1.236:${ASSET_PACK_PORT:-7413}/
      - AUTH_SERVER_URL=http://192.168.1.236:${AUTH_PORT:-9413}
      - APP_VERSION=2.7.2
      - ASSET_DIR=/assets/
    volumes:
      - ../:/app
      - ../assets/AssetPackV2Lite:/assets
    depends_on:
      - asset_server
      - auth_server

  asset_server:
    build:
      context: ..
      dockerfile: docker/asset_server/Dockerfile
    ports:
      - "${ASSET_PACK_PORT:-7413}:${ASSET_PACK_PORT:-7413}"
    volumes:
      - ../assets/AssetPackV2Lite:/assets
      # For Unraid deployment, you can replace the relative path with a direct path:
      # - /path/to/your/assets:/assets
    environment:
      - ASSET_DIR=/assets

  auth_server:
    build:
      context: ..
      dockerfile: docker/auth_server/Dockerfile
    ports:
      - "${AUTH_PORT:-9413}:${AUTH_PORT:-9413}"
    volumes:
      - /Users/jennyleidig/Documents/Projects/unofficial-homestuck-collection-web/servers/auth_server/db:/data
      # For Unraid deployment, you can replace the absolute path with a direct path:
      # - /path/to/your/auth/db:/data
    environment:
      - DB_PATH=/data/db.sqlite