version: '3.8'

services:
  webapp:
    build:
      context: ..
      dockerfile: docker/webapp/Dockerfile
      args:
        - ASSET_PACK_HREF=[PUT SERVER HOSTNAME]:${ASSET_PACK_PORT:-7413}/
        - AUTH_SERVER_URL=[PUT SERVER HOSTNAME]:${AUTH_PORT:-9413}
        - APP_VERSION=2.7.2
        - ASSET_DIR=/assets/
    ports:
      - "${WEB_PORT:-8413}:80"
    environment:
      - ASSET_PACK_HREF=[PUT SERVER HOSTNAME]:${ASSET_PACK_PORT:-7413}/
      - AUTH_SERVER_URL=[PUT SERVER HOSTNAME]:${AUTH_PORT:-9413}
      - APP_VERSION=2.7.2
      - ASSET_DIR=/assets/
    volumes:
      - {HOST_PATH_TO_ASSETS}:/assets
    depends_on:
      - asset_server
      - auth_server

  asset_server:
    build:
      context: ..
      dockerfile: docker/asset_server/Dockerfile
    ports:
      - "${ASSET_PACK_PORT:-7413}:${ASSET_PACK_PORT:-7413}"
    volumes:
      - {HOST_PATH_TO_ASSETS}:/assets
      # For Unraid deployment, you can replace the named volume with a direct path:
      # - /path/to/your/assets:/assets
    environment:
      - ASSET_DIR=/assets

  auth_server:
    build:
      context: ..
      dockerfile: docker/auth_server/Dockerfile
    ports:
      - "${AUTH_PORT:-9413}:${AUTH_PORT:-9413}"
    volumes:
      - {HOST_PATH_TO_AUTH_DB}:/data
      # For Unraid deployment, you can replace the named volume with a direct path:
      # - /path/to/your/auth/db:/data
    environment:
      - DB_PATH=/data/db.sqlite

